rollout_fn:
  _target_: src.runners.gymnasium_runner.make_rollout_fn
  _partial_: true
  num_steps: ${algorithm.num_steps}
  num_envs: ${algorithm.num_envs}

eval_fn:
  _target_: src.runners.gymnasium_runner.make_eval_fn
  _partial_: true
  max_episode_steps: ${algorithm.max_episode_steps}
  max_eval_episodes: 1000

train_fn:
  _target_: src.algorithms.training.make_loop_train_fn
  _partial_: true
  num_steps: ${algorithm.num_steps}
  total_time_steps: ${algorithm.total_time_steps}
  num_envs: ${algorithm.num_envs}
  num_eval: ${algorithm.num_eval}
  max_episode_steps: ${algorithm.max_episode_steps}
  train_log_interval: 1
  stochastic_eval: False