rollout_fn:
  _target_: src.runners.torch_cuda_runner.make_rollout_fn
  _partial_: true
  num_steps: ${algorithm.num_steps}
  num_envs: ${algorithm.num_envs}

eval_fn:
  _target_: src.runners.torch_cuda_runner.make_eval_fn
  _partial_: true
  max_episode_steps: ${algorithm.max_episode_steps}
  
train_fn:
  _target_: src.algorithms.training.make_loop_train_fn
  _partial_: true
  num_steps: ${algorithm.num_steps}
  total_time_steps: ${algorithm.total_time_steps}
  num_envs: ${algorithm.num_envs}
  num_eval: ${algorithm.num_eval}
  max_episode_steps: ${algorithm.max_episode_steps}
  stochastic_eval: True