type: maniskill
name: PushCube-v1
reconfiguration_freq: null
eval_reconfiguration_freq: 1
partial_reset: true
eval_partial_reset: false
asymmetric_obs: false
max_episode_steps: 50
stochastic_eval: true
has_final_obs: true
control_mode: pd_joint_delta_pos
capture_video: false
save_train_video_freq: null
render_mode: rgb_array
env_kwargs:
  obs_mode: state
  sim_backend: physx_cuda
vmin: -15
vmax: 15
