env:
  name: PickCube-v1
  reconfiguration_freq: null
  eval_reconfiguration_freq: 1
  partial_reset: true
  eval_partial_reset: false
  asymmetric_obs: false
  max_episode_steps: 50
  stochastic_eval: true
  has_final_obs: true
  control_mode: pd_joint_delta_pos
  capture_video: false
  save_train_video_freq: null
  env_kwargs:
    obs_mode: state
    render_mode: rgb_array
    sim_backend: physx_cuda

seed: 226
num_seeds: 1
num_envs: 1024
num_steps: 64
num_eval: 1000
total_time_steps: 1000000
num_mini_batches: 32
num_epochs: 8
learning_rate: 3e-4
anneal_lr: false
max_grad_norm: 0.5
gamma: 0.99
lmbda: 0.95
kl_start: 0.01
kl_bound: 0.1
ent_start: 0.001
ent_target_mult: 0.5
num_bins: 151
vmin: 0.0
vmax: 150.0
aux_loss_coeff: 0.0
num_action_samples: 64 # used to approximate the state value function
jit: true